server:
  port: 8001
spring:
  application:
    name: provider8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://114.215.176.111:3306/baseinfo?userUnicode=true&haracterEncoding=UTF-8&userSSL=false
    username: root
    password: yinbenyang
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.seven.cloud.entity
